owner: arcstur
repo: homelab-status

sites:
  - name: Nextcloud
    url: https://nextcloud.arcstur.com

assignees:
  - arcstur

workflowSchedule:
  uptime: "*/15 * * * *"

status-website:
  cname: status.arcstur.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Homelab Status
  introTitle: "Artur's homelab status monitoring."
  introMessage: "Status updates from the services and apps I run :-)"
  navbar:
    - title: GitHub
      href: https://github.com/arcstur/homelab-status
